Repository CodeSoom/dev-interview-kwonmory, pull requests merged in 2020-08, with the labels that each got.

#13 개발 환경 추가 구성하기
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  codecept.conf.js
  index.html
  jest.config.js
  mocks/api/auth/POST.json
  mocks/api/categories/GET.json
  mocks/api/problems/GET.json
  mocks/api/problems/README.md
  mocks/api/users/1/POST.json
  package-lock.json
  package.json
  src/index.css
  steps.d.ts
  steps_file.js
  test/header_test.js
  webpack.config.js
Labels: enhancement

#14 인터뷰 페이지 초안 작성
  .github/workflows/ci.yml
  fixtures/interview-questions.js
  fixtures/term.js
  package.json
  src/App.jsx
  src/App.test.jsx
  src/components/common/Header.jsx
  src/components/common/Header.test.jsx
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/modules/utils.js
  src/modules/utils.test.js
  src/pages/InterviewPracticePage.jsx
  src/pages/InterviewPracticePage.test.jsx
  webpack.config.js
Labels: enhancement

#15 Fix ci for add access_token
  .github/workflows/ci.yml
Labels: bug

#16 Update Interview Questions List Part in InterviewPracticePage
  fixtures/interview-questions.js
  index.html
  jest.setup.js
  mocks/api/problems/GET.json
  package-lock.json
  package.json
  src/App.test.jsx
  src/containers/InterviewQuestionsContainer.jsx
  src/containers/InterviewQuestionsContainer.test.jsx
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewPracticePage.jsx
  src/pages/InterviewPracticePage.test.jsx
  src/services/__mocks__/api.js
  src/services/api.js
  src/services/api.test.js
  webpack.config.js
Labels: enhancement

#17 Fix publicPath for github pages deploy
  webpack.config.js
Labels: bug

#19 Supplement the content about webpack config
  package.json
  webpack.config.js
Labels: enhancement

#20 Remove redundant await use
  src/modules/reducer.js
Labels: good first issue

#21 Add the part that brings up the categories in InterviewCategoriesContainer
  fixtures/interview-questions.js
  fixtures/parts.js
  mocks/api/README.md
  mocks/api/auth/README.md
  mocks/api/categories/GET.json
  mocks/api/categories/README.md
  mocks/api/parts/GET.json
  mocks/api/problems/GET.json
  mocks/api/problems/README.md
  mocks/api/questions/1/GET.json
  mocks/api/questions/GET.json
  src/App.test.jsx
  src/containers/InterviewCategoriesContainer.jsx
  src/containers/InterviewCategoriesContainer.test.jsx
  src/containers/InterviewQuestionsContainer.jsx
  src/containers/InterviewQuestionsContainer.test.jsx
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewPracticePage.jsx
  src/pages/InterviewPracticePage.test.jsx
  src/services/__mocks__/api.js
  src/services/api.js
  src/services/api.test.js
Labels: enhancement

#22 Update any parts that need to be updated in relation to the Interview Practice Page
  fixtures/interview-categories.js
  fixtures/parts.js
  mocks/api/interview/categories/GET.json
  mocks/api/interview/questions/1/GET.json
  mocks/api/interview/questions/GET.json
  mocks/api/interview/questions/POST.json
  mocks/api/parts/GET.json
  src/App.jsx
  src/App.test.jsx
  src/components/CategoriesList.jsx
  src/components/CategoriesList.test.jsx
  src/components/CategoryItem.jsx
  src/components/CategoryItem.test.jsx
  src/components/InterviewCategories.jsx
  src/components/InterviewCategories.test.jsx
  src/components/InterviewQuestions.jsx
  src/components/InterviewQuestions.test.jsx
  src/components/QuestionItem.jsx
  src/components/QuestionItem.test.jsx
  src/components/QuestionList.jsx
  src/components/QuestionList.test.jsx
  src/components/common/Header.jsx
  src/containers/InterviewCategoriesContainer.jsx
  src/containers/InterviewCategoriesContainer.test.jsx
  src/containers/InterviewQuestionsContainer.jsx
  src/containers/InterviewQuestionsContainer.test.jsx
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewPracticePage.jsx
  src/pages/InterviewPracticePage.test.jsx
  src/services/api.js
  src/services/api.test.js
Labels: enhancement

#31 API 데이터 구조를 추가하라 외 2건
  fixtures/interview-questions.js
  mocks/api/interview/question/1/GET.json
  mocks/api/interview/questions/1/GET.json
  mocks/api/interview/questions/GET.json
  mocks/api/interview/questions/POST.json
  mocks/api/users/1/POST.json
  mocks/api/users/README.md
  src/pages/NotFoundPage.jsx
  src/pages/NotFoundPage.test.jsx
  src/services/api.js
Labels: enhancement

#32 Apply Not Found Page
  src/App.jsx
  src/App.test.jsx
Labels: enhancement

#34 Update readme
  README.md
Labels: documentation

#36 Add InterviewPage
  __mocks__/react-redux.js
  fixtures/interviews.js
  mocks/api/interviews/GET.json
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewsPage.jsx
  src/pages/InterviewsPage.test.jsx
  src/services/api.js
  src/services/api.test.js
Labels: enhancement

#39 Apply design to Interivews
  assets/images/interviews-default.png
  fixtures/interviews.js
  mocks/api/interviews/GET.json
  package-lock.json
  package.json
  src/App.test.jsx
  src/components/Interviews.jsx
  src/components/Interviews.test.jsx
  src/components/InterviewsItem.jsx
  src/components/InterviewsItem.test.jsx
  src/containers/InterviewsContainer.jsx
  webpack.config.js
Labels: enhancement

#40 Update Header Area
  babel.config.js
  package.json
  src/components/common/Header.jsx
  src/components/common/Header.test.jsx
  src/containers/common/HeaderContainer.jsx
  src/containers/common/HeaderContainer.test.jsx
Labels: enhancement

#41 Update Header
  src/components/common/Header.jsx
  src/components/common/Header.test.jsx
  src/css/react-transitions.css
  src/index.css
  src/index.jsx
Labels: enhancement

#42 Fix Header Link Style
  src/components/common/Header.jsx
Labels: enhancement

#43 Make QuizIntroPage
  assets/images/avichu.png
  fixtures/quiz.js
  mocks/api/quiz/1/GET.json
  mocks/api/quiz/2/GET.json
  mocks/api/quiz/3/GET.json
  src/App.jsx
  src/components/Interviews.jsx
  src/components/InterviewsItem.jsx
  src/components/quiz/QuizErrorMessage.jsx
  src/components/quiz/QuizErrorMessage.test.jsx
  src/components/quiz/QuizIntro.jsx
  src/components/quiz/QuizIntro.test.jsx
  src/containers/common/QuizHeaderContainer.jsx
  src/containers/common/QuizHeaderContainer.test.jsx
  src/containers/quiz/QuizIntroContainer.jsx
  src/containers/quiz/QuizIntroContainer.test.jsx
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewPracticePage.jsx
  src/pages/InterviewsIntroPage.jsx
  src/pages/InterviewsIntroPage.test.jsx
  src/pages/InterviewsPage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/NotFoundPage.test.jsx
  src/services/api.js
  src/services/api.test.js
Labels: enhancement

#44 Make move from the interviews page to the interviews intro page
  mocks/api/quiz/2/GET.json
  mocks/api/quiz/3/GET.json
  src/components/Interviews.jsx
  src/components/Interviews.test.jsx
  src/components/InterviewsItem.jsx
  src/components/InterviewsItem.test.jsx
  src/components/quiz/QuizIntro.jsx
  src/containers/InterviewsContainer.jsx
  src/containers/InterviewsContainer.test.jsx
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewsIntroPage.jsx
Labels: enhancement

#45 Add Layouts
  src/layout/BaseLayout.jsx
  src/layout/BaseLayout.test.jsx
  src/layout/InterviewsLayout.jsx
  src/layout/InterviewsLayout.test.jsx
  src/pages/InterviewPracticePage.jsx
  src/pages/InterviewsIntroPage.jsx
  src/pages/InterviewsPage.jsx
  src/pages/NotFoundPage.jsx
Labels: enhancement

#46 Add interviews header
  src/components/common/QuizHeader.jsx
  src/components/common/QuizHeader.test.jsx
  src/components/quiz/QuizErrorMessage.jsx
  src/containers/common/QuizHeaderContainer.jsx
  src/containers/common/QuizHeaderContainer.test.jsx
  src/layout/InterviewsLayout.jsx
  src/layout/InterviewsLayout.test.jsx
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewsIntroPage.jsx
  src/pages/InterviewsIntroPage.test.jsx
  src/pages/NotFoundPage.jsx
Labels: enhancement

#50 Make draft interviews problem page
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/ConfirmAlert.jsx
  src/components/common/ConfirmAlert.test.jsx
  src/components/quiz/QuizErrorMessage.jsx
  src/components/quiz/QuizIntro.jsx
  src/containers/InterviewsContainer.jsx
  src/containers/InterviewsContainer.test.jsx
  src/containers/common/QuizHeaderContainer.jsx
  src/containers/common/QuizHeaderContainer.test.jsx
  src/containers/quiz/QuizIntroContainer.jsx
  src/containers/quiz/QuizIntroContainer.test.jsx
  src/index.css
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewsProblemPage.jsx
  src/pages/InterviewsProblemPage.test.jsx
Labels: enhancement

#52 Change quiz api property name for readability
  fixtures/quiz.js
  src/pages/InterviewsProblemPage.jsx
  src/pages/InterviewsProblemPage.test.jsx
  src/services/api.test.js
Labels: enhancement

#53 Override react-confirm-alert-overlay animation duration
  src/index.css
Labels: enhancement

#54 Add interviews problems timer
  mocks/api/quiz/1/GET.json
  mocks/api/quiz/2/GET.json
  mocks/api/quiz/3/GET.json
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/ButtonStyled.jsx
  src/components/common/QuizHeader.jsx
  src/components/common/QuizHeader.test.jsx
  src/components/quiz/QuizErrorMessage.jsx
  src/components/quiz/QuizIntro.jsx
  src/layout/InterviewsLayout.jsx
  src/pages/InterviewsIntroPage.jsx
  src/pages/InterviewsIntroPage.test.jsx
  src/pages/InterviewsProblemPage.jsx
  src/pages/InterviewsProblemPage.test.jsx
Labels: enhancement

#55 Add feedback page
  package-lock.json
  package.json
  src/App.jsx
  src/containers/common/QuizHeaderContainer.test.jsx
  src/index.css
  src/index.jsx
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewsFeedBackPage.jsx
  src/pages/InterviewsFeedBackPage.test.jsx
  src/pages/InterviewsProblemPage.jsx
  src/pages/InterviewsProblemPage.test.jsx
  src/services/__mock__/storage.js
  src/services/storage.js
  src/services/storage.test.js
Labels: enhancement

#57 Add FinishPage And CheckPage
  src/App.jsx
  src/components/common/ButtonStyled.jsx
  src/layout/InterviewsLayout.jsx
  src/modules/reducer.js
  src/modules/reducer.test.js
  src/pages/InterviewsCheckPage.jsx
  src/pages/InterviewsCheckPage.test.jsx
  src/pages/InterviewsFeedBackPage.jsx
  src/pages/InterviewsFeedBackPage.test.jsx
  src/pages/InterviewsFinishPage.jsx
  src/pages/InterviewsFinishPage.test.jsx
Labels: enhancement

#58 Remove text in QuizIntro
  src/components/quiz/QuizIntro.jsx
Labels: enhancement

#59 Refactoring pages
  src/components/quiz/InterviewsCheck.jsx
  src/components/quiz/InterviewsCheck.test.jsx
  src/components/quiz/InterviewsFeedBack.jsx
  src/components/quiz/InterviewsFeedBack.test.jsx
  src/components/quiz/InterviewsFinish.jsx
  src/components/quiz/InterviewsFinish.test.jsx
  src/containers/quiz/InterviewsCheckContainer.jsx
  src/containers/quiz/InterviewsCheckContainer.test.jsx
  src/containers/quiz/InterviewsFeedBackContainer.jsx
  src/containers/quiz/InterviewsFeedBackContainer.test.jsx
  src/containers/quiz/InterviewsFinishContainer.jsx
  src/containers/quiz/InterviewsFinishContainer.test.jsx
  src/pages/InterviewsCheckPage.jsx
  src/pages/InterviewsFeedBackPage.jsx
  src/pages/InterviewsFinishPage.jsx
Labels: enhancement
